"""Mermaid diagram renderer — generates Mermaid code via Qwen and renders to PNG.

Rendering options (in priority order):
  1. mmdc (Mermaid CLI) — best quality, requires Node
  2. Mermaid.ink API — no local install needed (fallback)
  3. Raw .mmd file only — always saved

Includes smart post-processing to fix common LLM diagram mistakes:
  - Single-letter node labels (e.g. X[J]) → removed or expanded
  - Dangling references to undefined nodes
  - Parentheses inside bracket labels
"""
from __future__ import annotations

import os
import re
import subprocess
import shutil
import time
import base64
from datetime import datetime
from typing import Optional, Dict, List, Set, Tuple
from collections import defaultdict

import requests

from pipeline.pipeline_config import PipelineConfig


def sanitize_mermaid(code: str) -> str:
    """Fix common Mermaid syntax issues generated by LLMs.

    Multi-pass repair:
      1. Strip markdown fences
      2. Fix parentheses inside bracket labels
      3. Detect & remove bogus single-char label nodes (e.g. X[J])
      4. Rewrite dangling edges that reference removed nodes
      5. Remove empty lines and trailing whitespace
    """
    if not code:
        return code

    # ── Pass 0: Strip markdown fences ────────────────────────────────
    code = re.sub(r"^```(?:mermaid)?\s*", "", code.strip())
    code = re.sub(r"\s*```$", "", code.strip())

    # ── Pass 0b: Fix leading dots/punctuation before diagram type ─────
    code = re.sub(r"^[.\s]+(?=sequenceDiagram|flowchart|graph|classDiagram)", "", code, flags=re.IGNORECASE)

    # For sequence diagrams, clean up and shorten labels
    first_line = next((l.strip() for l in code.split('\n') if l.strip() and not l.strip().startswith('%%')), '')
    if first_line.lower().startswith('sequencediagram'):
        lines = code.split('\n')
        cleaned = []
        # Regex: captures  "Source ->> Target: Label"  or  "Source -->> Target: Label"
        arrow_re = re.compile(r'^(\s*)(\w+)\s*(--?>>)\s*(\w+)\s*:\s*(.+)$')
        for line in lines:
            stripped = line.strip()
            if not stripped:
                continue
            m = arrow_re.match(stripped)
            if m:
                indent = "    "
                src = m.group(2)
                arrow = m.group(3)
                dst = m.group(4)
                label = m.group(5).strip()
                # Remove special chars: periods, question marks, commas, parentheses, quotes
                label = re.sub(r"[.?!\"'()\[\]]", "", label).strip()
                # If label is too long (>50 chars), take first 5 words
                if len(label) > 50:
                    words = label.split()
                    label = ' '.join(words[:5]).strip()
                cleaned.append(f"{indent}{src}{arrow}{dst}: {label}")
            else:
                cleaned.append(line)
        code = '\n'.join(cleaned)
        return code.strip()

    # ── Pass 1: Fix node labels with parentheses inside brackets ─────
    def _fix_bracket_label(m):
        prefix = m.group(1)
        label = m.group(2)
        suffix = m.group(3)
        label = label.replace('(', '- ').replace(')', '')
        label = re.sub(r'\s+', ' ', label).strip().rstrip('-').strip()
        return f"{prefix}{label}{suffix}"

    code = re.sub(r'(\w+\[)([^\]]+)(\])', _fix_bracket_label, code)

    # ── Pass 2: Detect all node definitions and find broken ones ─────
    # A node definition looks like:  ID[Label]  or  ID(Label)  or  ID{Label}  etc.
    node_def_pattern = re.compile(r'\b([A-Za-z_]\w*)\[([^\]]*)\]')
    node_defs: Dict[str, str] = {}   # id → label
    bogus_nodes: Set[str] = set()

    for match in node_def_pattern.finditer(code):
        node_id = match.group(1)
        label = match.group(2).strip()

        # Skip Mermaid keywords
        if node_id.lower() in ('subgraph', 'end', 'flowchart', 'graph', 'style', 'classDef',
                                 'click', 'linkStyle', 'direction'):
            continue

        node_defs[node_id] = label

        # Flag nodes with single-character labels (the core bug)
        if len(label) <= 1:
            bogus_nodes.add(node_id)

    # ── Pass 3: Remove lines that define or reference bogus nodes ────
    if bogus_nodes:
        clean_lines = []
        for line in code.split('\n'):
            stripped = line.strip()
            # Skip empty/comment lines — keep them
            if not stripped or stripped.startswith('%%'):
                clean_lines.append(line)
                continue

            # Check if this line defines a bogus node or has an edge to/from one
            has_bogus = False
            for bn in bogus_nodes:
                # Check if the bogus node appears as a node definition or edge endpoint
                # Patterns: BN[...], --> BN, BN -->, BN ---
                if re.search(rf'\b{re.escape(bn)}\b', stripped):
                    has_bogus = True
                    break

            if has_bogus:
                # Try to salvage: if line has a valid node on one side, keep
                # that connection to a reasonable target. Otherwise, drop.
                #
                # For now, just drop lines with bogus nodes — they're noise.
                continue
            clean_lines.append(line)
        code = '\n'.join(clean_lines)

    # ── Pass 4: Remove duplicate edges ───────────────────────────────
    seen_edges = set()
    final_lines = []
    edge_pattern = re.compile(r'^\s*(\w+)\s*[-=][-=]*>?\|?[^|]*\|?\s*(\w+)')
    for line in code.split('\n'):
        m = edge_pattern.match(line.strip())
        if m:
            edge_key = (m.group(1), m.group(2))
            if edge_key in seen_edges:
                continue
            seen_edges.add(edge_key)
        final_lines.append(line)
    code = '\n'.join(final_lines)

    # ── Pass 5: Clean up residual issues ─────────────────────────────
    # Remove stray double-quotes and backslashes inside labels
    code = re.sub(r'[\\]', '', code)
    # Remove empty lines in the body (but keep header and subgraph structure)
    lines = code.split('\n')
    code = '\n'.join(l for l in lines if l.strip() or l == '')

    return code.strip()


def validate_mermaid(code: str) -> Tuple[bool, List[str]]:
    """Validate Mermaid code structure and return (is_valid, issues).

    Checks:
      - Has a diagram type declaration
      - All referenced nodes are defined somewhere
      - No single-character labels remain
      - At least 3 nodes and 2 edges exist
    """
    issues = []
    if not code:
        return False, ["Empty mermaid code"]

    lines = [l.strip() for l in code.split('\n') if l.strip()]

    # Check diagram type
    first_meaningful = next((l for l in lines if l and not l.startswith('%%')), '')
    if not re.match(r'^(flowchart|graph|sequenceDiagram|classDiagram|erDiagram|gantt|pie)', first_meaningful):
        issues.append(f"Missing or invalid diagram type declaration: '{first_meaningful[:40]}'")

    # Collect all node definitions (ID[label], ID(label), ID{{label}})
    node_def_re = re.compile(r'\b([A-Za-z_]\w*)[\[\(\{]([^\]\)\}]+)[\]\)\}]')
    keywords = {'subgraph', 'end', 'flowchart', 'graph', 'style', 'classdef',
                'click', 'linkstyle', 'direction', 'participant', 'td', 'lr', 'tb', 'rl'}
    defined_nodes: Dict[str, str] = {}
    for m in node_def_re.finditer(code):
        nid = m.group(1)
        if nid.lower() not in keywords:
            defined_nodes[nid] = m.group(2).strip()

    # Check for labels that are too short
    for nid, label in defined_nodes.items():
        if len(label) <= 1:
            issues.append(f"Node '{nid}' has a meaningless single-char label: [{label}]")

    # Count edges
    edge_re = re.compile(r'\w+\s*[-=][-=]*>?\|?[^|]*\|?\s*\w+')
    edges = edge_re.findall(code)

    # For sequence diagrams, count participants and messages instead of nodes/edges
    is_sequence = bool(re.match(r'^sequenceDiagram', first_meaningful, re.IGNORECASE))
    if is_sequence:
        participants = re.findall(r'participant\s+\w+', code)
        messages = re.findall(r'->>|-->>|->', code)
        if len(participants) < 2:
            issues.append(f"Too few participants ({len(participants)}), expected at least 2")
        if len(messages) < 3:
            issues.append(f"Too few messages ({len(messages)}), expected at least 3")
    else:
        if len(defined_nodes) < 3:
            issues.append(f"Too few nodes ({len(defined_nodes)}), expected at least 3")
        if len(edges) < 2:
            issues.append(f"Too few edges ({len(edges)}), expected at least 2")

    return len(issues) == 0, issues


class DiagramGenerator:
    """Generates and renders Mermaid diagrams with validation."""

    MAX_RETRIES = 2  # Retry diagram generation if validation fails

    def __init__(self):
        PipelineConfig.ensure_dirs()
        self._mmdc = shutil.which("mmdc")
        if self._mmdc:
            print("✅ Mermaid CLI (mmdc) found — local rendering enabled")
        else:
            print("⚠️  mmdc not found — using mermaid.ink API for rendering")

    def render(
        self,
        mermaid_code: str,
        output_name: Optional[str] = None,
        fmt: str = "png",
    ) -> Dict[str, str]:
        """Render Mermaid code to an image file.

        Returns dict with keys: mmd_file, image_file, method
        """
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        name = output_name or f"diagram_{ts}"
        mmd_file = os.path.join(PipelineConfig.DIAGRAMS_DIR, f"{name}.mmd")
        img_file = os.path.join(PipelineConfig.DIAGRAMS_DIR, f"{name}.{fmt}")

        # Sanitize before saving/rendering
        mermaid_code = sanitize_mermaid(mermaid_code)

        # Validate the diagram quality
        is_valid, issues = validate_mermaid(mermaid_code)
        if not is_valid:
            print(f"⚠️  Diagram validation warnings: {'; '.join(issues)}")
        else:
            print("✅ Diagram passed validation checks")

        # Always save .mmd
        with open(mmd_file, "w") as f:
            f.write(mermaid_code)
        print(f"💾 Mermaid source saved: {mmd_file}")

        method = "mmd_only"

        # Try mmdc first
        if self._mmdc:
            try:
                result = subprocess.run(
                    [self._mmdc, "-i", mmd_file, "-o", img_file, "-b", "transparent"],
                    capture_output=True,
                    text=True,
                    timeout=30,
                )
                if result.returncode == 0 and os.path.exists(img_file):
                    method = "mmdc"
                    print(f"🖼️  Diagram rendered (mmdc): {img_file}")
                    return {"mmd_file": mmd_file, "image_file": img_file, "method": method}
                else:
                    print(f"⚠️  mmdc failed: {result.stderr[:200]}")
            except Exception as e:
                print(f"⚠️  mmdc error: {e}")

        # Fallback: mermaid.ink API
        try:
            encoded = base64.urlsafe_b64encode(mermaid_code.encode()).decode()
            url = f"https://mermaid.ink/img/{encoded}"
            resp = requests.get(url, timeout=15)
            if resp.status_code == 200:
                with open(img_file, "wb") as f:
                    f.write(resp.content)
                method = "mermaid.ink"
                print(f"🖼️  Diagram rendered (mermaid.ink): {img_file}")
                return {"mmd_file": mmd_file, "image_file": img_file, "method": method}
            else:
                print(f"⚠️  mermaid.ink returned {resp.status_code}")
        except Exception as e:
            print(f"⚠️  mermaid.ink error: {e}")

        print(f"📝 Only .mmd source saved (rendering unavailable)")
        return {"mmd_file": mmd_file, "image_file": None, "method": method}

    def render_from_analysis(self, analysis_data: Dict) -> Dict[str, str]:
        """Extract mermaid_code from analysis result, validate, and render."""
        data = analysis_data.get("analysis", analysis_data)
        mermaid_code = data.get("mermaid_code", "")
        if not mermaid_code:
            raise ValueError("No mermaid_code found in analysis data")
        title = data.get("title", "").replace(" ", "_").lower()[:30] or "diagram"

        # Log extracted components if available (for debugging)
        components = data.get("components_extracted", [])
        if components:
            print(f"   📋 Components identified: {', '.join(components[:10])}"
                  + (f" (+{len(components)-10} more)" if len(components) > 10 else ""))

        return self.render(mermaid_code, output_name=title)
