"""Project Specification Generator — produces a polished, client-facing PDF.

Creates a "Cahier des Charges" style document that consolidates all pipeline
outputs into a professional project specification:
  - Executive Summary
  - Project Context & Objectives
  - Functional Requirements (numbered, categorized)
  - Non-Functional Requirements
  - System Architecture Overview (with ASCII diagrams rendered cleanly)
  - Data Model & API Design
  - Security & Integration
  - Project Timeline & Team Estimates
  - Risk Assessment
  - Open Items & Next Steps
  - Appendix: System Diagram

Designed to be a middle-ground document that both clients and technical
teams can understand.
"""
from __future__ import annotations

import os
import time
from datetime import datetime
from typing import Dict, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    HRFlowable,
    Image,
    KeepTogether,
)

from pipeline.pipeline_config import PipelineConfig

# ── Brand colours ─────────────────────────────────────────────────────────────

BRAND = {
    "primary":    "#b45309",   # amber-700
    "dark":       "#451a03",   # amber-950
    "darker":     "#1c1917",   # stone-900
    "accent":     "#d97706",   # amber-500
    "light":      "#fef3c7",   # amber-100
    "bg_soft":    "#fffbeb",   # amber-50
    "text":       "#1c1917",
    "text_mid":   "#57534e",
    "text_light": "#a8a29e",
    "success":    "#10b981",
    "warning":    "#f59e0b",
    "danger":     "#ef4444",
    "info":       "#3b82f6",
    "border":     "#e7e5e4",
    "white":      "#ffffff",
}

W, H = A4  # 210mm x 297mm


# ── Page drawing callbacks ────────────────────────────────────────────────────

def _header_footer(canvas, doc, title="Project Specification"):
    """Draw header line and footer on every page."""
    canvas.saveState()
    # Top accent bar
    canvas.setFillColor(colors.HexColor(BRAND["primary"]))
    canvas.rect(0, H - 8 * mm, W, 8 * mm, fill=True, stroke=False)
    canvas.setFillColor(colors.HexColor(BRAND["light"]))
    canvas.setFont("Helvetica-Bold", 8)
    canvas.drawString(20 * mm, H - 6 * mm, title.upper())
    canvas.drawRightString(W - 20 * mm, H - 6 * mm, f"Page {doc.page}")
    # Bottom line
    canvas.setStrokeColor(colors.HexColor(BRAND["border"]))
    canvas.setLineWidth(0.5)
    canvas.line(20 * mm, 14 * mm, W - 20 * mm, 14 * mm)
    canvas.setFillColor(colors.HexColor(BRAND["text_light"]))
    canvas.setFont("Helvetica", 7)
    canvas.drawString(20 * mm, 10 * mm, f"Generated by ScribeAI — {datetime.now().strftime('%B %d, %Y')}")
    canvas.drawRightString(W - 20 * mm, 10 * mm, "Confidential")
    canvas.restoreState()


# ── Style factory ─────────────────────────────────────────────────────────────

def _spec_styles():
    ss = getSampleStyleSheet()

    styles = {}
    styles["CoverTitle"] = ParagraphStyle(
        "SpecCoverTitle", parent=ss["Title"],
        fontSize=32, leading=38, alignment=TA_CENTER,
        textColor=colors.HexColor(BRAND["dark"]),
        spaceAfter=4 * mm,
    )
    styles["CoverSubtitle"] = ParagraphStyle(
        "SpecCoverSub", parent=ss["Normal"],
        fontSize=14, leading=18, alignment=TA_CENTER,
        textColor=colors.HexColor(BRAND["text_mid"]),
        spaceAfter=8 * mm,
    )
    styles["CoverMeta"] = ParagraphStyle(
        "SpecCoverMeta", parent=ss["Normal"],
        fontSize=11, leading=16, alignment=TA_CENTER,
        textColor=colors.HexColor(BRAND["text_mid"]),
        spaceAfter=3 * mm,
    )
    styles["SectionNum"] = ParagraphStyle(
        "SectionNum", parent=ss["Normal"],
        fontSize=11, leading=14,
        textColor=colors.HexColor(BRAND["primary"]),
        fontName="Helvetica-Bold",
        spaceBefore=0,
    )
    styles["H1"] = ParagraphStyle(
        "SpecH1", parent=ss["Heading1"],
        fontSize=18, leading=22,
        textColor=colors.HexColor(BRAND["dark"]),
        spaceBefore=10 * mm, spaceAfter=4 * mm,
        fontName="Helvetica-Bold",
    )
    styles["H2"] = ParagraphStyle(
        "SpecH2", parent=ss["Heading2"],
        fontSize=13, leading=17,
        textColor=colors.HexColor(BRAND["primary"]),
        spaceBefore=6 * mm, spaceAfter=3 * mm,
        fontName="Helvetica-Bold",
    )
    styles["H3"] = ParagraphStyle(
        "SpecH3", parent=ss["Heading3"],
        fontSize=11, leading=14,
        textColor=colors.HexColor(BRAND["text"]),
        spaceBefore=4 * mm, spaceAfter=2 * mm,
        fontName="Helvetica-Bold",
    )
    styles["Body"] = ParagraphStyle(
        "SpecBody", parent=ss["Normal"],
        fontSize=10, leading=15,
        textColor=colors.HexColor(BRAND["text"]),
        alignment=TA_JUSTIFY,
        spaceAfter=3 * mm,
    )
    styles["BodySmall"] = ParagraphStyle(
        "SpecBodySm", parent=ss["Normal"],
        fontSize=9, leading=13,
        textColor=colors.HexColor(BRAND["text_mid"]),
        spaceAfter=2 * mm,
    )
    styles["BulletItem"] = ParagraphStyle(
        "SpecBullet", parent=ss["Normal"],
        fontSize=10, leading=14,
        textColor=colors.HexColor(BRAND["text"]),
        leftIndent=12, spaceAfter=2 * mm,
        bulletIndent=0, bulletFontSize=10,
    )
    styles["CalloutInfo"] = ParagraphStyle(
        "SpecCallout", parent=ss["Normal"],
        fontSize=10, leading=14,
        textColor=colors.HexColor("#1e40af"),
        backColor=colors.HexColor("#eff6ff"),
        borderPadding=8, borderWidth=1,
        borderColor=colors.HexColor("#bfdbfe"),
        spaceAfter=4 * mm,
    )
    styles["CalloutWarn"] = ParagraphStyle(
        "SpecCalloutW", parent=ss["Normal"],
        fontSize=10, leading=14,
        textColor=colors.HexColor(BRAND["dark"]),
        backColor=colors.HexColor(BRAND["bg_soft"]),
        borderPadding=8, borderWidth=1,
        borderColor=colors.HexColor("#fde68a"),
        spaceAfter=4 * mm,
    )
    styles["Code"] = ParagraphStyle(
        "SpecCode", parent=ss["Normal"],
        fontSize=7, leading=9,
        fontName="Courier",
        textColor=colors.HexColor(BRAND["text"]),
        backColor=colors.HexColor("#f8fafc"),
        borderPadding=8, borderWidth=1,
        borderColor=colors.HexColor(BRAND["border"]),
        spaceAfter=4 * mm,
    )
    styles["TOCEntry"] = ParagraphStyle(
        "SPECTOC", parent=ss["Normal"],
        fontSize=11, leading=18,
        textColor=colors.HexColor(BRAND["text"]),
        leftIndent=6, spaceAfter=1 * mm,
    )
    styles["Cell"] = ParagraphStyle(
        "SpecCell", parent=ss["Normal"],
        fontSize=9, leading=12,
        textColor=colors.HexColor(BRAND["text"]),
    )
    styles["CellBold"] = ParagraphStyle(
        "SpecCellB", parent=ss["Normal"],
        fontSize=9, leading=12,
        textColor=colors.HexColor(BRAND["text"]),
        fontName="Helvetica-Bold",
    )

    return styles


# ── Table helpers ─────────────────────────────────────────────────────────────

def _std_table_style(header_bg=BRAND["dark"], header_fg=BRAND["light"]):
    """Standard table styling for the specification."""
    return [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(header_bg)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor(header_fg)),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("LEADING", (0, 0), (-1, -1), 12),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor(BRAND["border"])),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]


def _zebra_rows(n_data_rows, color="#faf5f0"):
    """Generate alternating row background commands for n data rows."""
    cmds = []
    for i in range(2, n_data_rows + 1, 2):
        cmds.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor(color)))
    return cmds


PRIORITY_COLORS = {
    "high": colors.HexColor(BRAND["danger"]),
    "medium": colors.HexColor(BRAND["warning"]),
    "low": colors.HexColor(BRAND["success"]),
}
PRIORITY_LABELS = {"high": "High", "medium": "Medium", "low": "Low"}


# ── Generator class ───────────────────────────────────────────────────────────

class SpecificationGenerator:
    """Generates a polished Project Specification PDF from pipeline data."""

    def __init__(self):
        PipelineConfig.ensure_dirs()
        self.s = _spec_styles()

    # ── Public API ────────────────────────────────────────────────────

    def generate(
        self,
        pipeline_results: Dict,
        diagram_path: Optional[str] = None,
        output_file: Optional[str] = None,
    ) -> str:
        """Build the specification PDF. Returns the file path."""
        t0 = time.time()

        if not output_file:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_file = os.path.join(
                PipelineConfig.REPORTS_DIR, f"project_specification_{ts}.pdf"
            )

        doc = SimpleDocTemplate(
            output_file, pagesize=A4,
            leftMargin=20 * mm, rightMargin=20 * mm,
            topMargin=18 * mm, bottomMargin=20 * mm,
        )

        # Unpack the various analysis sections
        reqs = pipeline_results.get("requirements", {})
        summary = pipeline_results.get("summary", {})
        guidance = pipeline_results.get("consultant_guidance", {})
        amb = pipeline_results.get("ambiguity_detection", {})
        cq = pipeline_results.get("clarification_questions", {})
        arch = pipeline_results.get("system_architecture", {})
        mermaid_code = pipeline_results.get("mermaid_code", "")
        tech_stack = guidance.get("technology_stack_recommendation", {})
        req_spec = pipeline_results.get("requirements_spec", {})

        # Determine project title
        project_title = (
            reqs.get("title")
            or summary.get("title")
            or "Project Specification"
        )

        story = []

        # ── Cover Page ────────────────────────────────────────────
        story.append(Spacer(1, 50 * mm))
        story.append(HRFlowable(
            width="40%", thickness=2,
            color=colors.HexColor(BRAND["primary"]),
            spaceAfter=6 * mm,
        ))
        story.append(Paragraph(project_title, self.s["CoverTitle"]))
        story.append(Paragraph(
            "Project Specification Document",
            self.s["CoverSubtitle"],
        ))
        story.append(HRFlowable(
            width="40%", thickness=2,
            color=colors.HexColor(BRAND["primary"]),
            spaceAfter=20 * mm,
        ))

        # Cover metadata
        meta_items = [
            f"<b>Date:</b> {datetime.now().strftime('%B %d, %Y')}",
            f"<b>Version:</b> 1.0",
            f"<b>Status:</b> Draft",
        ]
        # Try to get project type from architecture or guidance
        project_type = arch.get("architecture_style", "")
        if not project_type:
            project_type = guidance.get("client_intent_summary", "")[:60] if guidance.get("client_intent_summary") else ""
        if project_type:
            meta_items.append(f"<b>Architecture:</b> {project_type}")

        for m in meta_items:
            story.append(Paragraph(m, self.s["CoverMeta"]))

        story.append(Spacer(1, 30 * mm))
        story.append(Paragraph(
            "<i>This document consolidates the analysis of recorded client meetings "
            "and provides a comprehensive specification for development.</i>",
            ParagraphStyle("CoverNote", parent=self.s["Body"],
                           alignment=TA_CENTER,
                           textColor=colors.HexColor(BRAND["text_light"]),
                           fontSize=9),
        ))

        story.append(PageBreak())

        # ── Table of Contents ─────────────────────────────────────
        toc_sections = [
            "1. Executive Summary",
            "2. Project Context & Objectives",
            "3. Functional Requirements",
            "4. Non-Functional Requirements",
            "5. System Architecture",
            "6. Data Model & API Design",
            "7. Security & Integration",
            "8. Technology Stack",
            "9. Risk Assessment & Warnings",
            "10. Requirements Specification",
            "11. Open Items & Next Steps",
            "12. Appendix: Diagrams",
        ]
        story.append(Paragraph("Table of Contents", self.s["H1"]))
        story.append(HRFlowable(
            width="100%", thickness=0.5,
            color=colors.HexColor(BRAND["border"]),
            spaceAfter=4 * mm,
        ))
        for sec in toc_sections:
            story.append(Paragraph(sec, self.s["TOCEntry"]))
        story.append(PageBreak())

        # ── Section counter ───────────────────────────────────────
        sec_num = [0]

        def section(title):
            sec_num[0] += 1
            story.append(Paragraph(f"SECTION {sec_num[0]}", self.s["SectionNum"]))
            story.append(Paragraph(title, self.s["H1"]))
            story.append(HRFlowable(
                width="100%", thickness=1,
                color=colors.HexColor(BRAND["primary"]),
                spaceAfter=4 * mm,
            ))

        # ══════════════════════════════════════════════════════════
        # 1. EXECUTIVE SUMMARY
        # ══════════════════════════════════════════════════════════
        section("Executive Summary")

        exec_summary = reqs.get("summary") or summary.get("summary") or ""
        if exec_summary:
            story.append(Paragraph(exec_summary, self.s["Body"]))

        intent = guidance.get("client_intent_summary", "")
        if intent:
            story.append(Paragraph(
                f"<b>Client Vision:</b> {intent}",
                self.s["CalloutInfo"],
            ))

        # Key metrics row
        metrics = []
        fr_count = len(reqs.get("functional_requirements", []))
        nfr_count = len(reqs.get("non_functional_requirements", []))
        amb_count = len(amb.get("ambiguities", []))
        risk_count = len(guidance.get("risk_areas", []))
        completeness = amb.get("completeness_score")

        if fr_count:
            metrics.append(("Functional Reqs", str(fr_count)))
        if nfr_count:
            metrics.append(("Non-Functional Reqs", str(nfr_count)))
        if amb_count:
            metrics.append(("Ambiguities Found", str(amb_count)))
        if risk_count:
            metrics.append(("Risk Areas", str(risk_count)))
        if completeness is not None:
            metrics.append(("Completeness", f"{int(float(completeness) * 100)}%"))

        if metrics:
            story.append(Spacer(1, 3 * mm))
            header_row = [m[0] for m in metrics]
            value_row = [m[1] for m in metrics]
            t = Table([header_row, value_row],
                      colWidths=[None] * len(metrics))
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(BRAND["dark"])),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor(BRAND["light"])),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor(BRAND["border"])),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor(BRAND["bg_soft"])),
            ]))
            story.append(t)

        story.append(PageBreak())

        # ══════════════════════════════════════════════════════════
        # 2. PROJECT CONTEXT & OBJECTIVES
        # ══════════════════════════════════════════════════════════
        section("Project Context &amp; Objectives")

        # Participants
        participants = summary.get("participants", [])
        if participants:
            story.append(Paragraph("Stakeholders Identified", self.s["H2"]))
            story.append(Paragraph(
                ", ".join(participants),
                self.s["Body"],
            ))

        # Topics discussed
        topics = summary.get("topics_discussed", [])
        if topics:
            story.append(Paragraph("Topics Discussed", self.s["H2"]))
            for t_item in topics:
                story.append(Paragraph(f"&bull; {t_item}", self.s["BulletItem"]))

        # Key decisions
        decisions = summary.get("key_decisions", [])
        if decisions:
            story.append(Paragraph("Key Decisions", self.s["H2"]))
            for d in decisions:
                story.append(Paragraph(f"&bull; {d}", self.s["BulletItem"]))

        # Key insights from consultant
        insights = guidance.get("key_insights", [])
        if insights:
            story.append(Paragraph("Key Insights", self.s["H2"]))
            for ins in insights:
                imp = ins.get("importance", "medium")
                color = {"high": BRAND["danger"], "medium": BRAND["warning"], "low": BRAND["success"]}.get(imp, BRAND["text_mid"])
                story.append(Paragraph(
                    f"<font color='{color}'><b>[{imp.upper()}]</b></font> {ins.get('insight', '')}",
                    self.s["Body"],
                ))

        story.append(PageBreak())

        # ══════════════════════════════════════════════════════════
        # 3. FUNCTIONAL REQUIREMENTS
        # ══════════════════════════════════════════════════════════
        section("Functional Requirements")

        fr_list = reqs.get("functional_requirements", [])
        if fr_list:
            story.append(Paragraph(
                "The following functional requirements have been extracted from the client meeting. "
                "Each requirement is assigned a priority level and unique identifier for traceability.",
                self.s["Body"],
            ))
            cell = self.s["Cell"]
            table_data = [["ID", "Requirement Description", "Priority"]]
            for fr in fr_list:
                p = fr.get("priority", "medium").lower()
                p_color = {"high": BRAND["danger"], "medium": BRAND["warning"], "low": BRAND["success"]}.get(p, BRAND["text_mid"])
                table_data.append([
                    Paragraph(f"<b>{fr.get('id', '-')}</b>", cell),
                    Paragraph(fr.get("description", ""), cell),
                    Paragraph(f"<font color='{p_color}'><b>{p.title()}</b></font>", cell),
                ])
            t = Table(table_data, colWidths=[22 * mm, None, 22 * mm])
            t.setStyle(TableStyle(_std_table_style() + _zebra_rows(len(fr_list))))
            story.append(t)
        else:
            story.append(Paragraph(
                "<i>No functional requirements were extracted from the meeting.</i>",
                self.s["BodySmall"],
            ))

        # Hidden / implied requirements
        hidden = guidance.get("hidden_requirements", [])
        if hidden:
            story.append(Spacer(1, 4 * mm))
            story.append(Paragraph("Implied Requirements", self.s["H2"]))
            story.append(Paragraph(
                "These requirements were not explicitly stated but are implied by the discussion:",
                self.s["BodySmall"],
            ))
            for h in hidden:
                story.append(Paragraph(f"&bull; {h}", self.s["BulletItem"]))

        story.append(PageBreak())

        # ══════════════════════════════════════════════════════════
        # 4. NON-FUNCTIONAL REQUIREMENTS
        # ══════════════════════════════════════════════════════════
        section("Non-Functional Requirements")

        nfr_list = reqs.get("non_functional_requirements", [])
        if nfr_list:
            story.append(Paragraph(
                "Non-functional requirements define the quality attributes and constraints of the system.",
                self.s["Body"],
            ))
            cell = self.s["Cell"]
            table_data = [["ID", "Description", "Category"]]
            for nfr in nfr_list:
                table_data.append([
                    Paragraph(f"<b>{nfr.get('id', '-')}</b>", cell),
                    Paragraph(nfr.get("description", ""), cell),
                    Paragraph(nfr.get("category", ""), cell),
                ])
            t = Table(table_data, colWidths=[22 * mm, None, 28 * mm])
            t.setStyle(TableStyle(_std_table_style() + _zebra_rows(len(nfr_list))))
            story.append(t)
        else:
            story.append(Paragraph(
                "<i>No non-functional requirements were explicitly identified.</i>",
                self.s["BodySmall"],
            ))

        story.append(PageBreak())

        # ══════════════════════════════════════════════════════════
        # 5. SYSTEM ARCHITECTURE
        # ══════════════════════════════════════════════════════════
        section("System Architecture")

        arch_overview = arch.get("architecture_overview", "")
        if arch_overview:
            story.append(Paragraph(arch_overview, self.s["Body"]))

        arch_style_name = arch.get("architecture_style", "")
        if arch_style_name:
            story.append(Paragraph(
                f"<b>Architecture Pattern:</b> {arch_style_name}",
                self.s["CalloutInfo"],
            ))

        # System layers
        layers = arch.get("system_layers", [])
        if layers:
            story.append(Paragraph("System Layers", self.s["H2"]))
            cell = self.s["Cell"]
            table_data = [["Layer", "Description", "Components", "Technologies"]]
            for layer in layers:
                comps = ", ".join(layer.get("components", []))
                techs = ", ".join(layer.get("technologies", []))
                table_data.append([
                    Paragraph(f"<b>{layer.get('name', '')}</b>", cell),
                    Paragraph(layer.get("description", ""), cell),
                    Paragraph(comps, cell),
                    Paragraph(f"<font color='{BRAND['primary']}'>{techs}</font>", cell),
                ])
            t = Table(table_data, colWidths=[28 * mm, None, 32 * mm, 32 * mm])
            t.setStyle(TableStyle(_std_table_style() + _zebra_rows(len(layers))))
            story.append(t)
            story.append(Spacer(1, 4 * mm))

        # ASCII System Architecture Diagram
        ascii_sys = arch.get("ascii_system_diagram", "")
        if ascii_sys:
            story.append(Paragraph("Architecture Overview Diagram", self.s["H2"]))
            safe = (ascii_sys
                    .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    .replace(" ", "&nbsp;").replace("\n", "<br/>"))
            story.append(Paragraph(safe, self.s["Code"]))

        # ASCII Data Flow
        ascii_df = arch.get("ascii_data_flow_diagram", "")
        if ascii_df:
            story.append(Paragraph("Data Flow", self.s["H2"]))
            safe = (ascii_df
                    .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    .replace(" ", "&nbsp;").replace("\n", "<br/>"))
            story.append(Paragraph(safe, self.s["Code"]))

        story.append(PageBreak())

        # ══════════════════════════════════════════════════════════
        # 6. DATA MODEL & API DESIGN
        # ══════════════════════════════════════════════════════════
        section("Data Model &amp; API Design")

        # Database schema
        db_schema = arch.get("database_schema", [])
        if db_schema:
            story.append(Paragraph("Data Model", self.s["H2"]))
            story.append(Paragraph(
                "The following entities have been identified based on the project requirements:",
                self.s["BodySmall"],
            ))
            for entity in db_schema:
                entity_name = entity.get("entity", "Unknown")
                story.append(Paragraph(
                    f"<b>{entity_name}</b>",
                    ParagraphStyle("EntityH", parent=self.s["H3"],
                                   textColor=colors.HexColor(BRAND["info"])),
                ))
                fields = entity.get("fields", [])
                if fields:
                    cell = self.s["Cell"]
                    table_data = [["Field", "Type", "Constraints"]]
                    for f in fields:
                        table_data.append([
                            Paragraph(f"<font name='Courier'>{f.get('name', '')}</font>", cell),
                            Paragraph(f.get("type", ""), cell),
                            Paragraph(f.get("constraints", ""), cell),
                        ])
                    t = Table(table_data, colWidths=[35 * mm, 30 * mm, None])
                    t.setStyle(TableStyle(_std_table_style(header_bg="#1e3a5f") + _zebra_rows(len(fields), "#f0f9ff")))
                    story.append(t)

                rels = entity.get("relationships", [])
                if rels:
                    for r_item in rels:
                        story.append(Paragraph(f"&rarr; {r_item}", self.s["BodySmall"]))
                story.append(Spacer(1, 3 * mm))

        # ER Diagram
        ascii_er = arch.get("ascii_er_diagram", "")
        if ascii_er:
            story.append(Paragraph("Entity-Relationship Diagram", self.s["H2"]))
            safe = (ascii_er
                    .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    .replace(" ", "&nbsp;").replace("\n", "<br/>"))
            story.append(Paragraph(safe, self.s["Code"]))

        # API Endpoints
        endpoints = arch.get("api_endpoints", [])
        if endpoints:
            story.append(Paragraph("API Endpoints", self.s["H2"]))
            story.append(Paragraph(
                "The following REST API endpoints are proposed for the system:",
                self.s["BodySmall"],
            ))
            cell = self.s["Cell"]
            method_colors = {
                "GET": BRAND["success"], "POST": BRAND["info"],
                "PUT": BRAND["warning"], "DELETE": BRAND["danger"],
                "PATCH": "#8b5cf6",
            }
            table_data = [["Method", "Endpoint", "Description"]]
            for ep in endpoints:
                method = ep.get("method", "GET").upper()
                m_color = method_colors.get(method, BRAND["text_mid"])
                table_data.append([
                    Paragraph(f"<font color='{m_color}'><b>{method}</b></font>", cell),
                    Paragraph(f"<font name='Courier'>{ep.get('path', '')}</font>", cell),
                    Paragraph(ep.get("description", ""), cell),
                ])
            t = Table(table_data, colWidths=[20 * mm, 45 * mm, None])
            t.setStyle(TableStyle(_std_table_style(header_bg="#0f172a", header_fg="#e2e8f0") + _zebra_rows(len(endpoints), "#f8fafc")))
            story.append(t)

        if not db_schema and not endpoints:
            story.append(Paragraph(
                "<i>Detailed data model and API design will be elaborated during the design phase.</i>",
                self.s["BodySmall"],
            ))

        story.append(PageBreak())

        # ══════════════════════════════════════════════════════════
        # 7. SECURITY & INTEGRATION
        # ══════════════════════════════════════════════════════════
        section("Security &amp; Integration")

        security = arch.get("security_architecture", {})
        if security:
            story.append(Paragraph("Security Architecture", self.s["H2"]))
            for key, val in security.items():
                if val:
                    label = key.replace("_", " ").title()
                    story.append(Paragraph(
                        f"<b>{label}:</b> {val}",
                        self.s["Body"],
                    ))

        integrations = arch.get("integration_points", [])
        if integrations:
            story.append(Paragraph("Integration Points", self.s["H2"]))
            cell = self.s["Cell"]
            table_data = [["System", "Protocol", "Direction", "Description"]]
            for ip in integrations:
                table_data.append([
                    Paragraph(f"<b>{ip.get('system', '')}</b>", cell),
                    Paragraph(ip.get("protocol", ""), cell),
                    Paragraph(ip.get("direction", "").title(), cell),
                    Paragraph(ip.get("description", ""), cell),
                ])
            t = Table(table_data, colWidths=[30 * mm, 22 * mm, 22 * mm, None])
            t.setStyle(TableStyle(_std_table_style() + _zebra_rows(len(integrations))))
            story.append(t)

        if not security and not integrations:
            story.append(Paragraph(
                "<i>Security requirements and integration points will be defined during detailed design.</i>",
                self.s["BodySmall"],
            ))

        story.append(PageBreak())

        # ══════════════════════════════════════════════════════════
        # 8. TECHNOLOGY STACK
        # ══════════════════════════════════════════════════════════
        section("Technology Stack")

        if tech_stack:
            for category_key, category_label in [
                ("frontend", "Frontend"),
                ("backend", "Backend"),
                ("database", "Database"),
                ("infrastructure", "Infrastructure & Deployment"),
            ]:
                items = tech_stack.get(category_key, [])
                if items:
                    story.append(Paragraph(category_label, self.s["H2"]))
                    cell = self.s["Cell"]
                    table_data = [["Technology", "Rationale", "Confidence", "Alternatives"]]
                    for item in items:
                        conf = item.get("confidence", "medium").lower()
                        conf_color = {"high": BRAND["success"], "medium": BRAND["warning"], "low": BRAND["danger"]}.get(conf, BRAND["text_mid"])
                        alts = ", ".join(item.get("alternatives", []))
                        table_data.append([
                            Paragraph(f"<b>{item.get('technology', '')}</b>", cell),
                            Paragraph(item.get("rationale", ""), cell),
                            Paragraph(f"<font color='{conf_color}'><b>{conf.title()}</b></font>", cell),
                            Paragraph(alts if alts else "—", self.s["BodySmall"]),
                        ])
                    t = Table(table_data, colWidths=[28 * mm, None, 20 * mm, 30 * mm])
                    t.setStyle(TableStyle(_std_table_style() + _zebra_rows(len(items))))
                    story.append(t)
                    story.append(Spacer(1, 4 * mm))

            # Third-party services
            services = tech_stack.get("third_party_services", [])
            if services:
                story.append(Paragraph("Third-Party Services", self.s["H2"]))
                for svc in services:
                    story.append(Paragraph(
                        f"<b>{svc.get('service', '')}</b> — {svc.get('purpose', '')}",
                        self.s["BulletItem"],
                    ))

            # Estimates
            complexity = tech_stack.get("estimated_complexity", "")
            timeline = tech_stack.get("estimated_timeline", "")
            team = tech_stack.get("team_composition_suggestion", {})

            if complexity or timeline or team:
                story.append(Paragraph("Project Estimates", self.s["H2"]))
                if complexity:
                    c_color = {"low": BRAND["success"], "medium": BRAND["warning"], "high": BRAND["danger"], "very_high": BRAND["danger"]}.get(complexity.lower(), BRAND["text_mid"])
                    story.append(Paragraph(
                        f"<b>Complexity:</b> <font color='{c_color}'><b>{complexity.replace('_', ' ').title()}</b></font>",
                        self.s["Body"],
                    ))
                if timeline:
                    story.append(Paragraph(f"<b>Estimated Timeline:</b> {timeline}", self.s["Body"]))
                if team:
                    role_labels = {
                        "frontend_developers": "Frontend Developers",
                        "backend_developers": "Backend Developers",
                        "ui_ux_designer": "UI/UX Designer",
                        "project_manager": "Project Manager",
                        "qa_engineer": "QA Engineer",
                    }
                    parts = []
                    for k, v in team.items():
                        if v and v > 0:
                            parts.append(f"{v} {role_labels.get(k, k.replace('_', ' ').title())}")
                    if parts:
                        story.append(Paragraph(f"<b>Recommended Team:</b> {', '.join(parts)}", self.s["Body"]))
        else:
            story.append(Paragraph(
                "<i>Technology stack recommendations are based on consultant guidance "
                "and should be validated during the technical design phase.</i>",
                self.s["BodySmall"],
            ))

        story.append(PageBreak())

        # ══════════════════════════════════════════════════════════
        # 9. RISK ASSESSMENT & WARNINGS
        # ══════════════════════════════════════════════════════════
        section("Risk Assessment &amp; Warnings")

        # Ambiguities
        ambiguities = amb.get("ambiguities", [])
        if ambiguities:
            story.append(Paragraph("Identified Ambiguities", self.s["H2"]))
            story.append(Paragraph(
                "The following items require clarification before development can proceed with confidence:",
                self.s["BodySmall"],
            ))
            cell = self.s["Cell"]
            table_data = [["ID", "Type", "Severity", "Issue", "Recommendation"]]
            for a in ambiguities:
                sev = a.get("severity", "minor").lower()
                sev_color = {"critical": BRAND["danger"], "major": BRAND["warning"], "minor": BRAND["success"]}.get(sev, BRAND["text_mid"])
                table_data.append([
                    Paragraph(f"<b>{a.get('id', '—')}</b>", cell),
                    Paragraph(a.get("type", "").replace("_", " ").title(), cell),
                    Paragraph(f"<font color='{sev_color}'><b>{sev.title()}</b></font>", cell),
                    Paragraph(a.get("issue_description", a.get("original_statement", "")), cell),
                    Paragraph(a.get("recommendation", ""), cell),
                ])
            t = Table(table_data, colWidths=[16 * mm, 22 * mm, 16 * mm, None, 40 * mm])
            t.setStyle(TableStyle(_std_table_style() + _zebra_rows(len(ambiguities))))
            story.append(t)
            story.append(Spacer(1, 4 * mm))

        # Risk areas
        risks = guidance.get("risk_areas", [])
        if risks:
            story.append(Paragraph("Risk Areas", self.s["H2"]))
            cell = self.s["Cell"]
            table_data = [["Area", "Risk Level", "Mitigation Strategy"]]
            for r_item in risks:
                rl = r_item.get("risk_level", "medium").lower()
                rl_color = {"high": BRAND["danger"], "medium": BRAND["warning"], "low": BRAND["success"]}.get(rl, BRAND["text_mid"])
                table_data.append([
                    Paragraph(f"<b>{r_item.get('area', '')}</b>", cell),
                    Paragraph(f"<font color='{rl_color}'><b>{rl.title()}</b></font>", cell),
                    Paragraph(r_item.get("mitigation", ""), cell),
                ])
            t = Table(table_data, colWidths=[40 * mm, 22 * mm, None])
            t.setStyle(TableStyle(_std_table_style() + _zebra_rows(len(risks))))
            story.append(t)
            story.append(Spacer(1, 4 * mm))

        # Warnings
        warnings = amb.get("warnings", [])
        if warnings:
            story.append(Paragraph("Project Warnings", self.s["H2"]))
            for w in warnings:
                sev = w.get("severity", "medium").lower()
                style = self.s["CalloutWarn"] if sev != "high" else ParagraphStyle(
                    "WarnHigh", parent=self.s["CalloutWarn"],
                    textColor=colors.HexColor(BRAND["danger"]),
                    borderColor=colors.HexColor(BRAND["danger"]),
                    backColor=colors.HexColor("#fef2f2"),
                )
                story.append(Paragraph(
                    f"<b>[{sev.upper()}]</b> {w.get('category', '').replace('_', ' ').title()}: "
                    f"{w.get('description', '')}",
                    style,
                ))

        if not ambiguities and not risks and not warnings:
            story.append(Paragraph(
                "No significant risks or ambiguities were identified at this stage.",
                self.s["Body"],
            ))

        story.append(PageBreak())

        # ══════════════════════════════════════════════════════════
        # 10. REQUIREMENTS SPECIFICATION (from Q&A session)
        # ══════════════════════════════════════════════════════════
        section("Requirements Specification")

        spec_content = req_spec.get("spec_content", "")
        answers_summary = req_spec.get("answers_summary", {})
        total_answered = req_spec.get("total_answered", 0)

        if spec_content or answers_summary:
            story.append(Paragraph(
                "This section captures the detailed requirements specification "
                "built through an interactive Q&amp;A session with stakeholders. "
                f"<b>{total_answered}</b> clarification questions were addressed.",
                self.s["Body"],
            ))

            # Q&A Answers table
            if answers_summary:
                story.append(Paragraph("Clarification Q&amp;A Summary", self.s["H2"]))
                cell = self.s["Cell"]
                table_data = [["Question ID", "Answer Provided"]]
                for q_id, answer in answers_summary.items():
                    if answer == '[Skipped]':
                        ans_display = Paragraph(
                            "<i><font color='#a8a29e'>Skipped</font></i>", cell
                        )
                    else:
                        # Truncate very long answers for table readability
                        display_text = answer if len(str(answer)) <= 200 else str(answer)[:200] + "…"
                        ans_display = Paragraph(display_text, cell)
                    table_data.append([
                        Paragraph(f"<b>{q_id}</b>", cell),
                        ans_display,
                    ])
                t = Table(table_data, colWidths=[28 * mm, None])
                t.setStyle(TableStyle(
                    _std_table_style() + _zebra_rows(len(answers_summary))
                ))
                story.append(t)
                story.append(Spacer(1, 6 * mm))

            # Full specification content
            if spec_content:
                story.append(Paragraph("Generated Specification", self.s["H2"]))
                # Render spec markdown as paragraphs (split by double-newline for sections)
                spec_blocks = spec_content.split("\n\n")
                for block in spec_blocks:
                    block = block.strip()
                    if not block:
                        continue
                    # Detect markdown headings
                    if block.startswith("### "):
                        story.append(Paragraph(block[4:], self.s["H3"]))
                    elif block.startswith("## "):
                        story.append(Paragraph(block[3:], self.s["H2"]))
                    elif block.startswith("# "):
                        story.append(Paragraph(
                            f"<b>{block[2:]}</b>", self.s["Body"]
                        ))
                    elif block.startswith("---"):
                        story.append(HRFlowable(
                            width="100%", thickness=0.5,
                            color=colors.HexColor(BRAND["border"]),
                            spaceAfter=3 * mm,
                        ))
                    elif block.startswith("- ") or block.startswith("* "):
                        # Bullet list
                        for line in block.split("\n"):
                            line = line.strip()
                            if line.startswith("- ") or line.startswith("* "):
                                safe_line = (line[2:]
                                             .replace("&", "&amp;")
                                             .replace("<", "&lt;")
                                             .replace(">", "&gt;"))
                                story.append(Paragraph(
                                    f"&bull; {safe_line}", self.s["BulletItem"]
                                ))
                    else:
                        safe_block = (block
                                      .replace("&", "&amp;")
                                      .replace("<", "&lt;")
                                      .replace(">", "&gt;")
                                      .replace("\n", "<br/>"))
                        story.append(Paragraph(safe_block, self.s["Body"]))
        else:
            story.append(Paragraph(
                "<i>No interactive requirements specification session was completed. "
                "Use the Requirements tab in the AI Assistant to build a detailed spec.</i>",
                self.s["BodySmall"],
            ))

        story.append(PageBreak())

        # ══════════════════════════════════════════════════════════
        # 11. OPEN ITEMS & NEXT STEPS
        # ══════════════════════════════════════════════════════════
        section("Open Items &amp; Next Steps")

        # Clarification questions
        cq_list = cq.get("questions", [])
        if cq_list:
            story.append(Paragraph("Questions Requiring Client Clarification", self.s["H2"]))
            must_ask = [q for q in cq_list if q.get("priority") == "must_ask"]
            should_ask = [q for q in cq_list if q.get("priority") == "should_ask"]
            nice = [q for q in cq_list if q.get("priority") == "nice_to_ask"]

            for label, group, color_bg in [
                ("Must Ask (Critical)", must_ask, "#fef2f2"),
                ("Should Ask (Important)", should_ask, BRAND["bg_soft"]),
                ("Nice to Ask", nice, "#f8fafc"),
            ]:
                if not group:
                    continue
                story.append(Paragraph(label, self.s["H3"]))
                for q in group:
                    story.append(Paragraph(
                        f"<b>&bull;</b> {q.get('question', '')}",
                        self.s["BulletItem"],
                    ))
                    ctx = q.get("context", "")
                    if ctx:
                        story.append(Paragraph(
                            f"<i>Context: {ctx}</i>",
                            ParagraphStyle("CtxNote", parent=self.s["BodySmall"], leftIndent=18),
                        ))

        # Action items
        actions = reqs.get("action_items", []) or summary.get("action_items", [])
        if actions:
            story.append(Paragraph("Action Items", self.s["H2"]))
            cell = self.s["Cell"]
            table_data = [["Owner", "Task", "Deadline"]]
            for a in actions:
                table_data.append([
                    Paragraph(f"<b>{a.get('owner', 'TBD')}</b>", cell),
                    Paragraph(a.get("task", ""), cell),
                    Paragraph(a.get("deadline", "TBD"), cell),
                ])
            t = Table(table_data, colWidths=[30 * mm, None, 28 * mm])
            t.setStyle(TableStyle(_std_table_style() + _zebra_rows(len(actions))))
            story.append(t)
            story.append(Spacer(1, 4 * mm))

        # Open questions
        open_q = reqs.get("open_questions", [])
        if open_q:
            story.append(Paragraph("Open Questions", self.s["H2"]))
            for q in open_q:
                story.append(Paragraph(f"&bull; {q}", self.s["BulletItem"]))

        # Recommended next steps
        next_steps = guidance.get("recommended_next_steps", [])
        if next_steps:
            story.append(Paragraph("Recommended Next Steps", self.s["H2"]))
            for i, step in enumerate(next_steps, 1):
                story.append(Paragraph(f"<b>{i}.</b> {step}", self.s["Body"]))

        # Meeting agenda
        agenda = cq.get("recommended_meeting_agenda", [])
        if agenda:
            story.append(Paragraph("Proposed Follow-Up Meeting Agenda", self.s["H2"]))
            for i, item in enumerate(agenda, 1):
                story.append(Paragraph(f"{i}. {item}", self.s["Body"]))

        story.append(PageBreak())

        # ══════════════════════════════════════════════════════════
        # 12. APPENDIX — DIAGRAMS
        # ══════════════════════════════════════════════════════════
        section("Appendix: Diagrams")

        # Embedded diagram image
        if diagram_path and os.path.exists(diagram_path):
            story.append(Paragraph("System Sequence Diagram", self.s["H2"]))
            try:
                img = Image(diagram_path, width=160 * mm, height=100 * mm)
                img.hAlign = "CENTER"
                story.append(img)
                story.append(Spacer(1, 4 * mm))
            except Exception as e:
                story.append(Paragraph(
                    f"<i>[Diagram image could not be embedded: {e}]</i>",
                    self.s["BodySmall"],
                ))

        # Mermaid source
        if mermaid_code:
            story.append(Paragraph("Diagram Source (Mermaid)", self.s["H2"]))
            safe_code = (mermaid_code
                         .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                         .replace(" ", "&nbsp;").replace("\n", "<br/>"))
            story.append(Paragraph(safe_code, self.s["Code"]))

        # Deployment diagram
        ascii_deploy = arch.get("ascii_deployment_diagram", "")
        if ascii_deploy:
            story.append(Paragraph("Deployment Diagram", self.s["H2"]))
            safe = (ascii_deploy
                    .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    .replace(" ", "&nbsp;").replace("\n", "<br/>"))
            story.append(Paragraph(safe, self.s["Code"]))

        # Infrastructure diagram
        ascii_infra = arch.get("ascii_infrastructure_diagram", "")
        if ascii_infra:
            story.append(Paragraph("Infrastructure Diagram", self.s["H2"]))
            safe = (ascii_infra
                    .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    .replace(" ", "&nbsp;").replace("\n", "<br/>"))
            story.append(Paragraph(safe, self.s["Code"]))

        # Scalability
        scalability = arch.get("scalability_strategy", "")
        if scalability:
            story.append(Paragraph("Scalability Strategy", self.s["H2"]))
            story.append(Paragraph(scalability, self.s["Body"]))

        monitoring = arch.get("monitoring_strategy", "")
        if monitoring:
            story.append(Paragraph("Monitoring Strategy", self.s["H2"]))
            story.append(Paragraph(monitoring, self.s["Body"]))

        # ── Build PDF ─────────────────────────────────────────────
        doc_title = project_title
        doc.build(
            story,
            onFirstPage=lambda c, d: _header_footer(c, d, doc_title),
            onLaterPages=lambda c, d: _header_footer(c, d, doc_title),
        )
        elapsed = time.time() - t0
        print(f"📋 Project Specification saved: {output_file} ({elapsed:.1f}s)")
        return output_file
