package com.aiuigenerator.bff.web;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.aiuigenerator.bff.domain.Generation;
import com.aiuigenerator.bff.repo.GenerationRepository;

import com.aiuigenerator.bff.dto.CodeBundleDto;
import com.aiuigenerator.bff.dto.CodeFileDto;
import com.aiuigenerator.bff.service.GenerationService;

@RestController
@RequestMapping("/api/generations")
public class ExportController {

    private final GenerationService service;
    private final GenerationRepository generationRepo;

    public ExportController(GenerationService service, GenerationRepository generationRepo) {
        this.service = service;
        this.generationRepo = generationRepo;
    }

    @GetMapping("/{id}/export")
    public ResponseEntity<byte[]> exportZip(@PathVariable("id") String generationId) {
        CodeBundleDto bundle;
        try {
            bundle = service.getCode(generationId);
        } catch (IllegalArgumentException e) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }

        List<CodeFileDto> files = bundle.files;
        if (files == null || files.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
        }

        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            try (ZipOutputStream zos = new ZipOutputStream(baos)) {
                for (CodeFileDto file : files) {
                    if (file.path == null || file.content == null) continue;
                    ZipEntry entry = new ZipEntry(file.path);
                    zos.putNextEntry(entry);
                    zos.write(file.content.getBytes(StandardCharsets.UTF_8));
                    zos.closeEntry();
                }
            }

            byte[] zipBytes = baos.toByteArray();
            String filename = "project-" + generationId.toLowerCase() + ".zip";

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.parseMediaType("application/zip"));
            headers.set(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"");
            headers.setContentLength(zipBytes.length);

            return new ResponseEntity<>(zipBytes, headers, HttpStatus.OK);

        } catch (IOException e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Clean Stack Export — same files but with professional folder structure,
     * .gitignore, and an auto-generated README.md injected into the ZIP.
     */
    @GetMapping("/{id}/export/clean")
    public ResponseEntity<byte[]> exportCleanZip(@PathVariable("id") String generationId) {
        CodeBundleDto bundle;
        Generation generation;
        try {
            bundle = service.getCode(generationId);
            generation = generationRepo.findById(generationId).orElse(null);
        } catch (IllegalArgumentException e) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }

        List<CodeFileDto> files = bundle.files;
        if (files == null || files.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
        }

        String prompt = generation != null && generation.getPrompt() != null ? generation.getPrompt() : "AI-generated UI";
        String globalScore = generation != null && generation.getGlobalScore() != null
                ? String.valueOf(generation.getGlobalScore()) : "N/A";

        // Build README content
        StringBuilder componentList = new StringBuilder();
        for (CodeFileDto f : files) {
            componentList.append("- `").append(f.path).append("`\n");
        }
        String readme = "# Generated UI Project\n\n"
                + "> Auto-generated by **Talanted** — AI-Powered UI Generator\n\n"
                + "## Overview\n" + prompt + "\n\n"
                + "## Tech Stack\n"
                + "- React 18 + TypeScript\n"
                + "- Tailwind CSS\n"
                + "- Vite\n\n"
                + "## Quality Score\n"
                + "Global Score: **" + globalScore + "/100**\n\n"
                + "## Project Structure\n"
                + "```\nsrc/\n  components/   → UI components\n  hooks/        → custom React hooks\n  utils/        → helpers & services\n```\n\n"
                + "## Components\n" + componentList + "\n"
                + "## Getting Started\n"
                + "```bash\nnpm install\nnpm run dev\n```\n\n"
                + "---\n*Generated by [Talanted](https://talanted.dev)*\n";

        String gitignore = "node_modules/\ndist/\n.env\n.env.local\n*.log\n.DS_Store\n";

        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            try (ZipOutputStream zos = new ZipOutputStream(baos)) {
                // Source files
                for (CodeFileDto file : files) {
                    if (file.path == null || file.content == null) continue;
                    ZipEntry entry = new ZipEntry(file.path);
                    zos.putNextEntry(entry);
                    zos.write(file.content.getBytes(StandardCharsets.UTF_8));
                    zos.closeEntry();
                }
                // README.md
                ZipEntry readmeEntry = new ZipEntry("README.md");
                zos.putNextEntry(readmeEntry);
                zos.write(readme.getBytes(StandardCharsets.UTF_8));
                zos.closeEntry();
                // .gitignore
                ZipEntry gitignoreEntry = new ZipEntry(".gitignore");
                zos.putNextEntry(gitignoreEntry);
                zos.write(gitignore.getBytes(StandardCharsets.UTF_8));
                zos.closeEntry();
            }

            byte[] zipBytes = baos.toByteArray();
            String filename = generationId.toLowerCase() + "-clean-stack.zip";
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.parseMediaType("application/zip"));
            headers.set(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"");
            headers.setContentLength(zipBytes.length);
            return new ResponseEntity<>(zipBytes, headers, HttpStatus.OK);

        } catch (IOException e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }
}
