# Direct SSH deploy — fallback when Jenkins/Ansible not available (Windows host)
# Copies config files to the VM and runs docker compose up via SSH.
# Usage: .\scripts\deploy-ssh.ps1 [-Tag latest]

param(
    [string]$Tag     = "latest",
    [string]$VM_IP   = "20.86.174.233",
    [string]$SSH_KEY = "$env:USERPROFILE\.ssh\azure_vm_key"
)

$ACR        = "aiuigeneratoracr.azurecr.io"
$ACR_USER   = "aiuigeneratoracr"
$ACR_PASS   = "8VqGCVlfnjXWlIc1tAJ0rbDbKDD2udolYW8Csj2uyLBoyljwUUi0JQQJ99CFAC5RqLJEqg7NAAACAZCRjT3Y"
$APP_DIR    = "/opt/ai-ui-generator"
$SSH_OPTS   = "-o StrictHostKeyChecking=no -i `"$SSH_KEY`""
$SSH_TARGET = "azureuser@$VM_IP"

$ErrorActionPreference = "Stop"
$Root = Split-Path $PSScriptRoot -Parent

function Run-SSH {
    param([string]$Cmd)
    $full = "ssh $SSH_OPTS $SSH_TARGET `"$Cmd`""
    Write-Host "> $Cmd" -ForegroundColor DarkGray
    Invoke-Expression $full
    if ($LASTEXITCODE -ne 0) { throw "SSH command failed: $Cmd" }
}

function SCP-Dir {
    param([string]$LocalPath, [string]$RemotePath)
    Write-Host "scp $LocalPath -> $RemotePath" -ForegroundColor DarkGray
    & scp -r $SSH_OPTS "$LocalPath" "${SSH_TARGET}:${RemotePath}"
    if ($LASTEXITCODE -ne 0) { throw "SCP failed: $LocalPath" }
}

Write-Host "=== Creating app directory ===" -ForegroundColor Cyan
Run-SSH "sudo mkdir -p $APP_DIR && sudo chown azureuser:azureuser $APP_DIR"

Write-Host "`n=== Copying docker-compose.prod.yml ===" -ForegroundColor Cyan
& scp $SSH_OPTS.Split(" ") "$Root\docker-compose.prod.yml" "${SSH_TARGET}:${APP_DIR}/docker-compose.yml"

Write-Host "`n=== Copying keycloak configs ===" -ForegroundColor Cyan
Run-SSH "mkdir -p $APP_DIR/keycloak"
SCP-Dir "$Root\keycloak" "$APP_DIR/"

Write-Host "`n=== Copying monitoring configs ===" -ForegroundColor Cyan
Run-SSH "mkdir -p $APP_DIR/monitoring/prometheus $APP_DIR/monitoring/grafana/provisioning"
SCP-Dir "$Root\monitoring\prometheus" "$APP_DIR/monitoring/"
SCP-Dir "$Root\monitoring\grafana\provisioning" "$APP_DIR/monitoring/grafana/"

Write-Host "`n=== Writing .env file ===" -ForegroundColor Cyan
$ENV_CONTENT = @"
# Generated by deploy-ssh.ps1
IMAGE_TAG=$Tag
ACR_LOGIN_SERVER=$ACR
VM_PUBLIC_IP=$VM_IP
MONGO_INITDB_DATABASE=ai_ui_generator
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
MINIO_BUCKET=ai-ui-files
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=admin
GROQ_API_KEY=$env:GROQ_API_KEY
GEMINI_API_KEY=$env:GEMINI_API_KEY
INTERNAL_API_SECRET=changeme-in-prod
ELEVENLABS_API_KEY=$env:ELEVENLABS_API_KEY
GRAFANA_PASSWORD=admin
APP_SECURITY_DEV_MODE=false
"@

# Write .env via SSH heredoc
$escaped = $ENV_CONTENT -replace '"', '\"'
Run-SSH "cat > $APP_DIR/.env << 'ENVEOF'`n$ENV_CONTENT`nENVEOF"

Write-Host "`n=== Installing Docker (if needed) ===" -ForegroundColor Cyan
Run-SSH @"
if ! command -v docker &>/dev/null; then
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker azureuser
fi
"@

Write-Host "`n=== Logging in to ACR ===" -ForegroundColor Cyan
Run-SSH "echo '$ACR_PASS' | docker login $ACR -u $ACR_USER --password-stdin"

Write-Host "`n=== Pulling images and starting services ===" -ForegroundColor Cyan
Run-SSH "cd $APP_DIR && docker compose pull && docker compose up -d --remove-orphans"

Write-Host "`n=== Deployment complete ===" -ForegroundColor Green
Write-Host "  Frontend : http://${VM_IP}:5173"
Write-Host "  API      : http://${VM_IP}:8081"
Write-Host "  Keycloak : http://${VM_IP}:8083"
Write-Host "  Grafana  : http://${VM_IP}:3000"
